### ISSUE TITLE
#20210209 交易日志

### ISSUE THREAD

**Issue by fddeth** [fddeth/tradingnotes#1]
价格从 69000 下跌回调，最终在 33000 左右筑底企稳，有向上通道趋势。

**Comment by fddeth** [comment]
- 序号：1
- 时间：0209
- 性质：试盘
- 方向：多
- 价格：44295
- 数量：1 btc
- 止损点：41000
- 突破点：45000
- 操作理由：突破 45000 之后开始回落，跌到 42000 + ，第二天起床之后，看到美股反转，btc 反弹 到44000+，很像是上升过程中的回调。于是开始建仓试盘。
- 图表：https://www.tradingview.com/x/UjZNTieP/

**Comment by LAOHUTOKEN** [comment]
牛

**Comment by fddeth** [comment]
价格又回到了 44000+ ，目前看还是上升通道形态，不过还不着急，还没有出现追加信号，只有突破 45000 才能操作。
过于急躁提前操作，是趋势交易的大忌，因为很容易被诱多。定好了规则，就需要严格遵守。扔掉那一点点利润，同时也避免了风险。

**Comment by fddeth** [comment]
序号：2
时间：0210
性质：追加
方向：多
价格：45100
数量：3.6 btc
止损点：42000
图表：https://www.tradingview.com/x/vZEGmBVu/

操作理由：突破 45100，按照之前设置的委托单自动市
价追加。

不过这次交易属于失败的追加交易。
价格突破之后，最高冲到45700，结果美国 CPI 数据出来，立刻来了一个暴跌，然后是一个 v 反，最高冲到 51900， 在睡觉时间内，又开始回落。

目前已经满仓状态，并且亏损，已经设置了止损点位，分别是 42000 和 41000。

这次的教训：

1、最好不要设置自动委托追加单，手动看情况是否追加。

2、要观察阻力位是否能够站稳，是不是只是插针，最好等待一两根线，看看多空力量对抗实力是否相当，如果相当就很危险。

3、前期止损低点，可以以前一个布尔带边缘水平线为基准，因为现在主力操盘，故意会砸破低点让一些趋势交易者止损（大家都知道趋势交易，主力可能就会故意打到那个点位）。

4、大幅放量之后，大概率会有回调，不要着急操作。

5、重大消息节点，盘面一般会有大幅震荡。如果不想冒险，可以先退出观望。（例如这次美国 CPI 公布，就反复震荡）

6、突破之后，追加不要满仓。

**Comment by fddeth** [comment]
昨天晚上下跌破了 42000，但是我的止损单并没有成交，应该是 FTX 的标记价格并没有达到这个点位。
周末没有美股干扰，看能不能稳住。

**Comment by fddeth** [comment]
下午一波急跌，已经被打止损。

此次交易总结：

1、参数还需要钝化调整，4h 线过于灵敏
2、建仓过于急躁，突破关键点位，应该进入试盘，而不是直接追加。应该遵循“不吃鱼头，只吃鱼身”的交易规则。
3、应该加入 ema200 均线作为参考。
4、方向不对，应该及时退出观望。
